info:
  name: Get task not found
  type: http
  seq: 1

http:
  method: GET
  url: http://localhost:3001/tasks/e7cb1723-345a-4918-b35b-4061bdc9f7f00
  auth:
    type: bearer
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmQ0MTQ5MS03Mzc2LTRjMDAtOWZlMi0yYWMzMTgzOGFlYTYiLCJlbWFpbCI6ImFybmF1ZGRuNkBnbWFpbC5jb20iLCJpYXQiOjE3OTA2ODQ1NDEsImV4cCI6MTc5MDc3MDk0MX0.w06N4ptSriPBjWv3xb0P3ySXCLlsogkpqAPo6mQviao

runtime:
  scripts:
    - type: tests
      code: |-
        test("Tâche inexistante renvoie 404", function () {
          expect(res.getStatus()).to.equal(404);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
